import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <img />
        <nav>
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((item) => (
          <a href={`/events/${item.id}`} key={item.id}>
            <Image src={item.image} width={170} height={100} alt={item.title} />
            <h2>{item.title}</h2>
            <p>{item.description}</p>
          </a>
        ))}
      </main>
    </>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("../../data/data.json");
  console.log(events_categories);
  return {
    props: {
      data: events_categories,
    },
  };
}
